server.port=${PORT:8080}

spring.application.name=medical-inventory-system


# =========================================================
# POSTGRESQL DATABASE
# =========================================================

spring.datasource.url=jdbc:postgresql://dpg-da5v59bncjis73a7ba50-a:5432/medical_inventory_b2s8

spring.datasource.username=medical_user

spring.datasource.password=MoEMX7hTz37yBWFDOwnAArYcnVrb2U9C

spring.datasource.driver-class-name=org.postgresql.Driver


# =========================================================
# JPA
# =========================================================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=true


# =========================================================
# JSON
# =========================================================

spring.jackson.serialization.fail-on-empty-beans=false


# =========================================================
# OLLAMA
# =========================================================

ollama.api.url=http://localhost:11434/api

ollama.model=llama3.2


# =========================================================
# EMAIL
# =========================================================

spring.mail.host=smtp.gmail.com

spring.mail.port=587

spring.mail.username=medicalinventory053@gmail.com

spring.mail.password=Govardhan@123

spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.starttls.enable=true


# =========================================================
# LOGGING
# =========================================================

logging.level.root=INFO

logging.level.com.medical.inventory=INFO


# =========================================================
# ERROR HANDLING
# =========================================================

server.error.include-message=always

server.error.include-binding-errors=always


# =========================================================
# CORS
# =========================================================

spring.web.cors.allowed-origins=http://localhost:5173

spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS

spring.web.cors.allowed-headers=*

spring.web.cors.allow-credentials=true